version: '3.8'

services:
  kafka1:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: C3pH83QrTo6mdrNxy65vsw
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: CONTROLLER://:9093,INTERNAL://:9094,CLIENT://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:9094,CLIENT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
    volumes:
      - kafka1-data:/var/lib/kafka/data

  kafka2:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka2
    ports:
      - "9093:9092"
    environment:
      CLUSTER_ID: C3pH83QrTo6mdrNxy65vsw
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: CONTROLLER://:9093,INTERNAL://:9094,CLIENT://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:9094,CLIENT://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
    volumes:
      - kafka2-data:/var/lib/kafka/data

  kafka3:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka3
    ports:
      - "9094:9092"
    environment:
      CLUSTER_ID: C3pH83QrTo6mdrNxy65vsw
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: CONTROLLER://:9093,INTERNAL://:9094,CLIENT://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:9094,CLIENT://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
    volumes:
      - kafka3-data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: kraft-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9094,kafka2:9094,kafka3:9094
      KAFKA_CLUSTERS_0_KAFKACONFIGPROPS_SECURITY_PROTOCOL: PLAINTEXT
      DYNAMIC_CONFIG_ENABLED: "true"
    depends_on:
      - kafka1
      - kafka2
      - kafka3

  create-topics:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - kafka-ui
    command: >
      bash -c "
        kafka-topics --bootstrap-server kafka1:9094,kafka2:9094 --create --topic practice2topic --partitions 3 --replication-factor 2 || exit 1
      "

  producer:
    build:
      context: .        
      dockerfile: cmd/producer/Dockerfile
    deploy:
      mode: replicated
      replicas: 2 
    depends_on:
      - create-topics
    restart: on-failure

  consumer1:
    build:
      context: .        
      dockerfile: cmd/consumer1/Dockerfile
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - create-topics
    restart: on-failure

  consumer2:
    build:
      context: .        
      dockerfile: cmd/consumer2/Dockerfile
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - create-topics
    restart: on-failure

volumes:
  kafka1-data:
  kafka2-data:
  kafka3-data: